import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export type Language = 'cs' | 'en' | 'de'
export type TranslationValues = Record<string, string | number>

export const languages: { value: Language; short: string; label: string }[] = [
  { value: 'cs', short: 'CS', label: 'Čeština' },
  { value: 'en', short: 'EN', label: 'English' },
  { value: 'de', short: 'DE', label: 'Deutsch' },
]

export const locales: Record<Language, string> = { cs: 'cs-CZ', en: 'en-GB', de: 'de-DE' }

const messages: Record<Language, Record<string, string>> = {
  cs: {
    'nav.dashboard': 'Přehled', 'nav.pantry': 'Zásoby', 'nav.freezer': 'Mrazák', 'nav.shopping': 'Nákupy', 'nav.recipes': 'Recepty', 'nav.todos': 'Úkoly', 'nav.settings': 'Nastavení',
    'brand.tagline': 'Všechno doma v klidu', 'common.add': 'Přidat', 'common.cancel': 'Zrušit', 'common.close': 'Zavřít', 'common.back': 'Zpět', 'common.restore': 'Obnovit', 'common.search': 'Hledat…', 'common.all': 'Vše', 'common.edit': 'Upravit', 'common.delete': 'Smazat', 'common.saveChanges': 'Uložit změny', 'common.items': '{count} položek', 'common.tasks': '{count} úkolů', 'common.results': '{count} výsledků', 'common.monthsShort': 'měs.', 'common.days': '{count} dny',
    'app.closeMenu': 'Zavřít menu', 'app.switchTheme': 'Přepnout vzhled', 'app.changeLanguage': 'Změnit jazyk', 'app.householdItems': 've vaší domácnosti', 'app.ecbRate': 'kurz ECB z {date}', 'app.localData': 'data jsou sdílená přes Home Assistant',
    'sync.loading': 'Načítám sdílená data z Home Assistantu…', 'sync.saving': 'Ukládám…', 'sync.synced': 'Synchronizováno', 'sync.error': 'Úložiště není dostupné',
    'search.placeholder': 'Hledat v zásobách, nákupech, receptech a úkolech…', 'search.title': 'Prohledejte celý Grocy Homie', 'search.hint': 'Fungují názvy, kategorie, EAN, ingredience, obchody i úkoly.', 'search.none': 'Nic jsme nenašli', 'search.noneHint': 'Zkuste kratší nebo obecnější výraz.', 'search.close': 'zavřít', 'search.archive': 'archiv',
    'settings.title': 'Nastavení Grocy Homie', 'settings.subtitle': 'Přizpůsobte vzhled domácnosti a předvyplněné hodnoty nových položek.', 'settings.reset': 'Obnovit výchozí', 'settings.resetDone': 'Výchozí nastavení bylo obnoveno', 'settings.household': 'Domácnost', 'settings.householdHint': 'Název se zobrazí v záhlaví na všech zařízeních.', 'settings.householdName': 'Název domácnosti', 'settings.householdPlaceholder': 'např. U Nováků', 'settings.currency': 'Výchozí měna', 'settings.language': 'Výchozí jazyk', 'settings.languageHint': 'Použije se při každém dalším otevření aplikace.', 'settings.czk': 'CZK — česká koruna', 'settings.eur': 'EUR — euro', 'settings.appearance': 'Vzhled', 'settings.appearanceHint': 'Režim a hlavní barva ovládacích prvků.', 'settings.theme': 'Barevný režim', 'settings.themeSystem': 'Podle zařízení', 'settings.themeLight': 'Světlý', 'settings.themeDark': 'Tmavý', 'settings.accent': 'Akcentní barva', 'settings.customColor': 'Vlastní barva', 'settings.defaults': 'Výchozí hodnoty zásob', 'settings.defaultsHint': 'Automaticky se předvyplní při každém přidání nové položky.', 'settings.category': 'Kategorie', 'settings.location': 'Umístění', 'settings.unit': 'Jednotka', 'settings.quantity': 'Množství', 'settings.minimum': 'Kanban minimum', 'settings.autoSave': 'Změny se automaticky ukládají do Home Assistantu a sdílejí mezi zařízeními.', 'settings.lists': 'Kategorie a umístění', 'settings.listsHint': 'Přidejte vlastní hodnoty nebo odeberte ty, které už nepoužíváte.', 'settings.newCategory': 'Nová kategorie', 'settings.newLocation': 'Nové umístění',
    'accent.coral': 'Korálová', 'accent.green': 'Šalvějová', 'accent.blue': 'Modrá', 'accent.plum': 'Švestková',
    'dashboard.greeting': 'Dobré odpoledne 👋', 'dashboard.lowOne': 'Ve spíži dochází 1 položka.', 'dashboard.lowMany': 'Ve spíži dochází {count} položky.', 'dashboard.stockGood': 'Zásoby vypadají dobře.', 'dashboard.calm': 'Pojďme udržet domácnost v klidu.', 'dashboard.openShopping': 'Otevřít nákup', 'dashboard.belowMinimum': '{count} pod minimem', 'dashboard.useSoon': '{count} brzy spotřebovat', 'dashboard.remaining': '{count} zbývá', 'dashboard.activeLists': '{count} aktivní seznamy', 'dashboard.stockValue': 'Hodnota zásob', 'dashboard.estimate': 'orientační součet', 'dashboard.attention': 'Vyžaduje pozornost', 'dashboard.attentionText': '{low} položky pod minimem · {expiring} položky brzy expirují', 'dashboard.check': 'Zkontrolovat', 'dashboard.kanban': 'Kanban zásob', 'dashboard.kanbanHint': 'Položky, které je čas doplnit', 'dashboard.allStock': 'Všechny zásoby', 'dashboard.minimum': 'minimum {count} {unit}', 'dashboard.stockOk': 'Všechny zásoby jsou nad minimem.', 'dashboard.todayTasks': 'Dnešní úkoly', 'dashboard.waiting': '{count} čeká na dokončení', 'dashboard.calendar': 'Kalendář', 'dashboard.todayDone': 'Na dnešek je hotovo.', 'dashboard.activity': 'Co se děje doma', 'dashboard.activityHint': 'Rychlý přehled termínů a zásob', 'dashboard.freezerUse': '{name} je čas spotřebovat', 'dashboard.inFreezerSince': 'V mrazáku od {date} · {progress} % doporučené doby', 'dashboard.expiring': '{name} brzy expiruje', 'dashboard.useBy': 'Spotřebujte do {date}', 'dashboard.noDeadlines': 'Žádné blížící se termíny.',
    'pantry.title': 'Co máme doma', 'pantry.subtitle': 'Mějte přehled, doplňujte jediným kliknutím a nic vám nedojde.', 'pantry.add': 'Přidat položku', 'pantry.search': 'Hledat v zásobách…', 'pantry.restock': 'Doplnit', 'pantry.expired': 'Po datu', 'pantry.minimum': 'Kanban minimum', 'pantry.until': 'do {date}', 'pantry.noExpiry': 'bez expirace', 'pantry.empty': 'Žádná položka neodpovídá filtru.',
    'freezer.title': 'Mrazák bez překvapení', 'freezer.subtitle': 'Doporučené doby při −18 °C hlídají nejlepší kvalitu potravin.', 'freezer.add': 'Přidat do mrazáku', 'freezer.goodToKnow': 'Dobré vědět', 'freezer.fact': 'Potraviny trvale skladované při −18 °C zůstávají bezpečné téměř neomezeně. Níže hlídáme doporučenou dobu pro nejlepší chuť a kvalitu.', 'freezer.contents': 'Obsah mrazáku', 'freezer.consume': 'Spotřebovat', 'freezer.soon': 'Brzy', 'freezer.ok': 'V pořádku', 'freezer.frozen': 'Zmraženo {date} · doporučeno {months} měs.', 'freezer.guide': 'Průvodce mražením', 'freezer.quality': 'Doporučení pro kvalitu', 'freezer.source': 'Zdroj: USDA Food Safety',
    'shopping.title': 'Nákupy pod kontrolou', 'shopping.subtitle': 'Seznamy podle obchodů, rychlé odškrtávání a přenos rovnou do zásob.', 'shopping.allArchived': 'Všechny aktivní seznamy jsou archivované.', 'shopping.restoreFirst': 'Nejprve obnovte seznam z archivu.', 'shopping.archived': 'Seznam „{name}“ byl archivován', 'shopping.restored': 'Seznam byl obnoven', 'shopping.finishedOne': 'Nákup dokončen · 1 položka přidána do zásob', 'shopping.finishedMany': 'Nákup dokončen · {count} položek přidáno do zásob', 'shopping.remaining': '{count} zbývá', 'shopping.newList': 'Nový seznam', 'shopping.archive': 'Archiv ({count})', 'shopping.archiveAction': 'Archivovat', 'shopping.scan': 'Skenovat kód', 'shopping.progress': 'Průběh nákupu', 'shopping.preselected': 'předvybráno pro zásoby', 'shopping.enterPrice': 'zadat cenu', 'shopping.spending': 'Průběžná útrata', 'shopping.done': 'Dokončeno', 'shopping.finishEyebrow': 'Dokončení nákupu', 'shopping.finishTitle': 'Co přidat do zásob?', 'shopping.finishText': 'Zaškrtnuté položky z nákupního seznamu budou označené jako vyřízené. Níže vyberte pouze potraviny, které chcete zároveň uložit do domácích zásob.', 'shopping.finishNote': 'Do zásob bude přidáno {selected} z {total} položek.', 'shopping.confirm': 'Potvrdit dokončení', 'shopping.archivedLists': 'Archivované seznamy', 'shopping.archivedHint': 'Uchované pro pozdější použití',
    'recipes.title': 'Co dnes uvaříme?', 'recipes.subtitle': 'Oblíbené recepty propojené s nákupem a domácími zásobami.', 'recipes.new': 'Nový recept', 'recipes.search': 'Hledat recept nebo ingredienci…', 'recipes.servings': '{count} porce', 'recipes.addShopping': 'Přidat ingredience na nákup', 'recipes.ingredientsAdded': 'Ingredience pro „{name}“ přidány na nákup', 'recipes.favorite': 'Oblíbený recept {name}',
    'todos.title': 'Co je potřeba zařídit', 'todos.subtitle': 'Úkoly domácnosti na jednom místě a v souvislostech.', 'todos.add': 'Přidat úkol', 'todos.selectedDay': 'Vybraný den', 'todos.empty': 'Na tento den nic nemáte.', 'weekdays': 'Po,Út,St,Čt,Pá,So,Ne',
    'modal.editItem': 'Upravit položku', 'modal.addPantry': 'Přidat do zásob', 'modal.addFreezer': 'Přidat do mrazáku', 'modal.addShopping': 'Přidat na nákup', 'modal.newTodo': 'Nový úkol', 'modal.scanCode': 'Skenovat kód', 'modal.editRecipe': 'Upravit recept', 'modal.newRecipe': 'Nový recept', 'modal.name': 'Název', 'modal.selectOrType': 'Vyberte nebo napište novou', 'modal.priceCzk': 'Cena v Kč', 'modal.purchaseDate': 'Datum nákupu', 'modal.expiryOptional': 'Spotřebovat do (volitelně)', 'modal.barcode': 'EAN / čárový kód', 'modal.scan': 'Skenovat', 'modal.imageUrl': 'Odkaz na obrázek', 'modal.photo': 'Vlastní fotografie', 'modal.productPreview': 'Náhled produktu', 'modal.choosePhoto': 'Vyfotit nebo vybrat obrázek', 'modal.changePhoto': 'Změnit fotografii', 'modal.freezerCategory': 'Kategorie a doporučená doba', 'modal.freezeDate': 'Datum zmrazení', 'modal.note': 'Poznámka', 'modal.list': 'Seznam', 'modal.estimatedPrice': 'Odhad ceny v Kč', 'modal.addToPantry': 'Předvybrat pro zásoby při dokončení nákupu', 'modal.todoQuestion': 'Co je potřeba udělat?', 'modal.date': 'Datum', 'modal.family': 'Rodina', 'modal.other': 'Jiné', 'modal.household': 'Domácnost', 'modal.emoji': 'Emoji', 'modal.recipeName': 'Název receptu', 'modal.minutes': 'Čas v minutách', 'modal.servings': 'Počet porcí', 'modal.tags': 'Štítky oddělené čárkou', 'modal.instructions': 'Postup', 'modal.instructionsPlaceholder': 'Popište jednotlivé kroky přípravy…', 'modal.exampleItem': 'např. Červené fazole', 'modal.exampleFreezer': 'např. Kuřecí stehna', 'modal.examplePortion': 'např. porce 500 g', 'modal.whatBuy': 'Co koupit?', 'modal.exampleTodo': 'např. Uklidit lednici', 'modal.exampleRecipe': 'např. Kuře na paprice', 'modal.tagsPlaceholder': 'Rychlé, Večeře, Vegetariánské', 'modal.codeScanned': 'Naskenován kód {code}', 'modal.eanLoaded': 'EAN {code} načten', 'modal.itemUpdated': 'Položka byla upravena', 'modal.itemPantryAdded': 'Položka přidána do zásob', 'modal.itemFreezerAdded': 'Položka přidána do mrazáku', 'modal.itemShoppingAdded': 'Položka přidána na nákup', 'modal.todoAdded': 'Úkol přidán', 'modal.recipeUpdated': 'Recept byl upraven', 'modal.recipeAdded': 'Recept byl přidán', 'modal.toTaste': 'dle chuti',
    'ingredients.title': 'Suroviny', 'ingredients.hint': 'Vyberte ze zásob nebo napište vlastní', 'ingredients.addRow': 'Přidat řádek', 'ingredients.item': 'Surovina', 'ingredients.amount': 'Množství suroviny {count}', 'ingredients.remove': 'Odebrat surovinu {count}', 'ingredients.amountPlaceholder': 'např. 500 g',
    'scanner.aim': 'Namiřte zadní kameru na čárový nebo QR kód.', 'scanner.https': 'Kamera vyžaduje otevření aplikace přes HTTPS. Zatím můžete EAN zadat ručně.', 'scanner.allow': 'Povolte kameru a podržte kód uvnitř rámečku.', 'scanner.denied': 'Přístup ke kameře nebyl povolen. Povolte jej v nastavení prohlížeče.', 'scanner.failed': 'Kameru se nepodařilo spustit. Zkontrolujte, zda ji nepoužívá jiná aplikace.', 'scanner.recognizing': 'Rozpoznávám kód z fotografie…', 'scanner.notFound': 'Na fotografii se nepodařilo najít kód. Zkuste jej vyfotit zblízka a bez odlesku.', 'scanner.stop': 'Zastavit', 'scanner.live': 'Živá kamera', 'scanner.photo': 'Vyfotit kód',
    'nutrition.title': 'Výživové hodnoty', 'nutrition.kcal': 'kcal', 'nutrition.per100': 'Údaje zadávejte na 100 g', 'nutrition.catalog': 'Kalorické tabulky', 'nutrition.searchFood': 'Vyhledat {name}', 'nutrition.openCatalog': 'Otevřít katalog potravin', 'nutrition.forAmount': 'Přepočítat pro množství', 'nutrition.carbs': 'Sacharidy', 'nutrition.fat': 'Tuky', 'nutrition.protein': 'Bílkoviny', 'nutrition.fiber': 'Vláknina', 'nutrition.amountAria': 'Množství pro přepočet makroživin',
    'error.photoRead': 'Fotografii se nepodařilo načíst.', 'error.photoFormat': 'Tento formát obrázku nelze použít.',
  },
  en: {},
  de: {},
}

Object.assign(messages.en, {
  'nav.dashboard':'Overview','nav.pantry':'Pantry','nav.freezer':'Freezer','nav.shopping':'Shopping','nav.recipes':'Recipes','nav.todos':'Tasks','nav.settings':'Settings','brand.tagline':'Everything at home, under control','common.add':'Add','common.cancel':'Cancel','common.close':'Close','common.back':'Back','common.restore':'Restore','common.search':'Search…','common.all':'All','common.edit':'Edit','common.delete':'Delete','common.saveChanges':'Save changes','common.items':'{count} items','common.tasks':'{count} tasks','common.results':'{count} results','common.monthsShort':'mo.','common.days':'{count} days',
  'app.closeMenu':'Close menu','app.switchTheme':'Switch theme','app.changeLanguage':'Change language','app.householdItems':'in your household','app.ecbRate':'ECB rate from {date}','app.localData':'data is shared through Home Assistant',
  'sync.loading':'Loading shared data from Home Assistant…','sync.saving':'Saving…','sync.synced':'Synced','sync.error':'Storage unavailable',
  'search.placeholder':'Search pantry, shopping, recipes and tasks…','search.title':'Search all of Grocy Homie','search.hint':'Search by name, category, EAN, ingredient, shop or task.','search.none':'No results found','search.noneHint':'Try a shorter or more general phrase.','search.close':'close','search.archive':'archive',
  'settings.title':'Grocy Homie settings','settings.subtitle':'Customise your household and the defaults for new items.','settings.reset':'Restore defaults','settings.resetDone':'Default settings restored','settings.household':'Household','settings.householdHint':'The name is shown in the header on every device.','settings.householdName':'Household name','settings.householdPlaceholder':'e.g. The Smiths','settings.currency':'Default currency','settings.language':'Default language','settings.languageHint':'Used whenever you open the app again.','settings.czk':'CZK — Czech koruna','settings.eur':'EUR — euro','settings.appearance':'Appearance','settings.appearanceHint':'Theme and primary control colour.','settings.theme':'Colour mode','settings.themeSystem':'Use device setting','settings.themeLight':'Light','settings.themeDark':'Dark','settings.accent':'Accent colour','settings.customColor':'Custom colour','settings.defaults':'Pantry defaults','settings.defaultsHint':'Pre-filled whenever you add a new item.','settings.category':'Category','settings.location':'Location','settings.unit':'Unit','settings.quantity':'Quantity','settings.minimum':'Kanban minimum','settings.autoSave':'Changes are saved to Home Assistant automatically and shared between devices.','settings.lists':'Categories and locations','settings.listsHint':'Add your own values or remove ones you no longer use.','settings.newCategory':'New category','settings.newLocation':'New location','accent.coral':'Coral','accent.green':'Sage','accent.blue':'Blue','accent.plum':'Plum',
  'dashboard.greeting':'Good afternoon 👋','dashboard.lowOne':'1 pantry item is running low.','dashboard.lowMany':'{count} pantry items are running low.','dashboard.stockGood':'Your pantry looks good.','dashboard.calm':'Let’s keep the household running smoothly.','dashboard.openShopping':'Open shopping','dashboard.belowMinimum':'{count} below minimum','dashboard.useSoon':'{count} use soon','dashboard.remaining':'{count} remaining','dashboard.activeLists':'{count} active lists','dashboard.stockValue':'Pantry value','dashboard.estimate':'estimated total','dashboard.attention':'Needs attention','dashboard.attentionText':'{low} below minimum · {expiring} expiring soon','dashboard.check':'Review','dashboard.kanban':'Pantry kanban','dashboard.kanbanHint':'Items that need restocking','dashboard.allStock':'All pantry items','dashboard.minimum':'minimum {count} {unit}','dashboard.stockOk':'All items are above their minimum.','dashboard.todayTasks':"Today's tasks",'dashboard.waiting':'{count} waiting','dashboard.calendar':'Calendar','dashboard.todayDone':'Everything is done for today.','dashboard.activity':'What is happening at home','dashboard.activityHint':'Quick overview of dates and stock','dashboard.freezerUse':'Time to use {name}','dashboard.inFreezerSince':'Frozen since {date} · {progress}% of recommended time','dashboard.expiring':'{name} expires soon','dashboard.useBy':'Use by {date}','dashboard.noDeadlines':'No upcoming dates.',
  'pantry.title':'What we have at home','pantry.subtitle':'Stay on top of stock, replenish with one click and never run out.','pantry.add':'Add item','pantry.search':'Search pantry…','pantry.restock':'Restock','pantry.expired':'Expired','pantry.minimum':'Kanban minimum','pantry.until':'until {date}','pantry.noExpiry':'no expiry date','pantry.empty':'No items match the filter.',
  'freezer.title':'A freezer without surprises','freezer.subtitle':'Recommended times at −18 °C help preserve the best quality.','freezer.add':'Add to freezer','freezer.goodToKnow':'Good to know','freezer.fact':'Food continuously stored at −18 °C stays safe almost indefinitely. The times below track the best flavour and quality.','freezer.contents':'Freezer contents','freezer.consume':'Use now','freezer.soon':'Soon','freezer.ok':'All good','freezer.frozen':'Frozen {date} · recommended {months} mo.','freezer.guide':'Freezing guide','freezer.quality':'Quality recommendations','freezer.source':'Source: USDA Food Safety',
  'shopping.title':'Shopping under control','shopping.subtitle':'Lists by shop, quick check-offs and direct transfer to the pantry.','shopping.allArchived':'All active lists are archived.','shopping.restoreFirst':'Restore a list from the archive first.','shopping.archived':'List “{name}” archived','shopping.restored':'List restored','shopping.finishedOne':'Shopping completed · 1 item added to pantry','shopping.finishedMany':'Shopping completed · {count} items added to pantry','shopping.remaining':'{count} remaining','shopping.newList':'New list','shopping.archive':'Archive ({count})','shopping.archiveAction':'Archive','shopping.scan':'Scan code','shopping.progress':'Shopping progress','shopping.preselected':'preselected for pantry','shopping.enterPrice':'enter price','shopping.spending':'Running total','shopping.done':'Complete','shopping.finishEyebrow':'Complete shopping','shopping.finishTitle':'What should be added to the pantry?','shopping.finishText':'Checked shopping-list items will be marked as completed. Select only the food you also want to store in the household pantry.','shopping.finishNote':'{selected} of {total} items will be added to the pantry.','shopping.confirm':'Confirm completion','shopping.archivedLists':'Archived lists','shopping.archivedHint':'Saved for later use',
  'recipes.title':'What shall we cook today?','recipes.subtitle':'Favourite recipes connected to shopping and household stock.','recipes.new':'New recipe','recipes.search':'Search recipe or ingredient…','recipes.servings':'{count} servings','recipes.addShopping':'Add ingredients to shopping','recipes.ingredientsAdded':'Ingredients for “{name}” added to shopping','recipes.favorite':'Favourite recipe {name}',
  'todos.title':'Things to take care of','todos.subtitle':'Household tasks in one place and in context.','todos.add':'Add task','todos.selectedDay':'Selected day','todos.empty':'Nothing scheduled for this day.','weekdays':'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
  'modal.editItem':'Edit item','modal.addPantry':'Add to pantry','modal.addFreezer':'Add to freezer','modal.addShopping':'Add to shopping','modal.newTodo':'New task','modal.scanCode':'Scan code','modal.editRecipe':'Edit recipe','modal.newRecipe':'New recipe','modal.name':'Name','modal.selectOrType':'Select or enter a new value','modal.priceCzk':'Price in CZK','modal.purchaseDate':'Purchase date','modal.expiryOptional':'Use by (optional)','modal.barcode':'EAN / barcode','modal.scan':'Scan','modal.imageUrl':'Image URL','modal.photo':'Custom photo','modal.productPreview':'Product preview','modal.choosePhoto':'Take or choose a photo','modal.changePhoto':'Change photo','modal.freezerCategory':'Category and recommended time','modal.freezeDate':'Freezing date','modal.note':'Note','modal.list':'List','modal.estimatedPrice':'Estimated price in CZK','modal.addToPantry':'Preselect for pantry when completing shopping','modal.todoQuestion':'What needs to be done?','modal.date':'Date','modal.family':'Family','modal.other':'Other','modal.household':'Household','modal.emoji':'Emoji','modal.recipeName':'Recipe name','modal.minutes':'Time in minutes','modal.servings':'Servings','modal.tags':'Comma-separated tags','modal.instructions':'Instructions','modal.instructionsPlaceholder':'Describe the preparation steps…','modal.exampleItem':'e.g. red beans','modal.exampleFreezer':'e.g. chicken thighs','modal.examplePortion':'e.g. 500 g portion','modal.whatBuy':'What should be bought?','modal.exampleTodo':'e.g. clean the fridge','modal.exampleRecipe':'e.g. paprika chicken','modal.tagsPlaceholder':'Quick, Dinner, Vegetarian','modal.codeScanned':'Scanned code {code}','modal.eanLoaded':'EAN {code} loaded','modal.itemUpdated':'Item updated','modal.itemPantryAdded':'Item added to pantry','modal.itemFreezerAdded':'Item added to freezer','modal.itemShoppingAdded':'Item added to shopping','modal.todoAdded':'Task added','modal.recipeUpdated':'Recipe updated','modal.recipeAdded':'Recipe added','modal.toTaste':'to taste',
  'ingredients.title':'Ingredients','ingredients.hint':'Choose from the pantry or enter your own','ingredients.addRow':'Add row','ingredients.item':'Ingredient','ingredients.amount':'Ingredient amount {count}','ingredients.remove':'Remove ingredient {count}','ingredients.amountPlaceholder':'e.g. 500 g',
  'scanner.aim':'Point the rear camera at a barcode or QR code.','scanner.https':'The camera requires HTTPS. You can enter the EAN manually for now.','scanner.allow':'Allow camera access and keep the code inside the frame.','scanner.denied':'Camera access was denied. Allow it in your browser settings.','scanner.failed':'The camera could not start. Check whether another app is using it.','scanner.recognizing':'Reading code from photo…','scanner.notFound':'No code was found in the photo. Try a close-up without glare.','scanner.stop':'Stop','scanner.live':'Live camera','scanner.photo':'Take code photo',
  'nutrition.title':'Nutrition facts','nutrition.kcal':'kcal','nutrition.per100':'Enter values per 100 g','nutrition.catalog':'Calorie tables','nutrition.searchFood':'Search for {name}','nutrition.openCatalog':'Open food catalogue','nutrition.forAmount':'Calculate for amount','nutrition.carbs':'Carbohydrates','nutrition.fat':'Fat','nutrition.protein':'Protein','nutrition.fiber':'Fibre','nutrition.amountAria':'Amount for nutrition calculation','error.photoRead':'The photo could not be read.','error.photoFormat':'This image format cannot be used.',
})

Object.assign(messages.de, {
  'nav.dashboard':'Übersicht','nav.pantry':'Vorräte','nav.freezer':'Gefrierschrank','nav.shopping':'Einkäufe','nav.recipes':'Rezepte','nav.todos':'Aufgaben','nav.settings':'Einstellungen','brand.tagline':'Zu Hause alles im Griff','common.add':'Hinzufügen','common.cancel':'Abbrechen','common.close':'Schließen','common.back':'Zurück','common.restore':'Wiederherstellen','common.search':'Suchen…','common.all':'Alle','common.edit':'Bearbeiten','common.delete':'Löschen','common.saveChanges':'Änderungen speichern','common.items':'{count} Artikel','common.tasks':'{count} Aufgaben','common.results':'{count} Ergebnisse','common.monthsShort':'Mon.','common.days':'{count} Tage',
  'app.closeMenu':'Menü schließen','app.switchTheme':'Darstellung wechseln','app.changeLanguage':'Sprache ändern','app.householdItems':'in deinem Haushalt','app.ecbRate':'EZB-Kurs vom {date}','app.localData':'Daten werden über Home Assistant geteilt',
  'sync.loading':'Gemeinsame Daten werden aus Home Assistant geladen…','sync.saving':'Speichern…','sync.synced':'Synchronisiert','sync.error':'Speicher nicht verfügbar',
  'search.placeholder':'Vorräte, Einkäufe, Rezepte und Aufgaben durchsuchen…','search.title':'Ganz Grocy Homie durchsuchen','search.hint':'Suche nach Name, Kategorie, EAN, Zutat, Geschäft oder Aufgabe.','search.none':'Keine Ergebnisse','search.noneHint':'Versuche einen kürzeren oder allgemeineren Begriff.','search.close':'schließen','search.archive':'Archiv',
  'settings.title':'Grocy-Homie-Einstellungen','settings.subtitle':'Passe deinen Haushalt und die Standardwerte für neue Artikel an.','settings.reset':'Standard wiederherstellen','settings.resetDone':'Standardeinstellungen wiederhergestellt','settings.household':'Haushalt','settings.householdHint':'Der Name erscheint auf allen Geräten in der Kopfzeile.','settings.householdName':'Name des Haushalts','settings.householdPlaceholder':'z. B. Familie Müller','settings.currency':'Standardwährung','settings.language':'Standardsprache','settings.languageHint':'Wird beim nächsten Öffnen der App verwendet.','settings.czk':'CZK — Tschechische Krone','settings.eur':'EUR — Euro','settings.appearance':'Darstellung','settings.appearanceHint':'Modus und Hauptfarbe der Bedienelemente.','settings.theme':'Farbmodus','settings.themeSystem':'Geräteeinstellung','settings.themeLight':'Hell','settings.themeDark':'Dunkel','settings.accent':'Akzentfarbe','settings.customColor':'Eigene Farbe','settings.defaults':'Standardwerte für Vorräte','settings.defaultsHint':'Wird beim Hinzufügen eines Artikels vorausgefüllt.','settings.category':'Kategorie','settings.location':'Lagerort','settings.unit':'Einheit','settings.quantity':'Menge','settings.minimum':'Kanban-Minimum','settings.autoSave':'Änderungen werden automatisch in Home Assistant gespeichert und zwischen Geräten geteilt.','settings.lists':'Kategorien und Lagerorte','settings.listsHint':'Füge eigene Werte hinzu oder entferne nicht mehr benötigte.','settings.newCategory':'Neue Kategorie','settings.newLocation':'Neuer Lagerort','accent.coral':'Koralle','accent.green':'Salbei','accent.blue':'Blau','accent.plum':'Pflaume',
  'dashboard.greeting':'Guten Tag 👋','dashboard.lowOne':'1 Vorratsartikel wird knapp.','dashboard.lowMany':'{count} Vorratsartikel werden knapp.','dashboard.stockGood':'Deine Vorräte sehen gut aus.','dashboard.calm':'Halten wir den Haushalt entspannt am Laufen.','dashboard.openShopping':'Einkauf öffnen','dashboard.belowMinimum':'{count} unter Minimum','dashboard.useSoon':'{count} bald verbrauchen','dashboard.remaining':'{count} übrig','dashboard.activeLists':'{count} aktive Listen','dashboard.stockValue':'Vorratswert','dashboard.estimate':'geschätzte Summe','dashboard.attention':'Aufmerksamkeit erforderlich','dashboard.attentionText':'{low} unter Minimum · {expiring} laufen bald ab','dashboard.check':'Prüfen','dashboard.kanban':'Vorrats-Kanban','dashboard.kanbanHint':'Artikel zum Nachfüllen','dashboard.allStock':'Alle Vorräte','dashboard.minimum':'Minimum {count} {unit}','dashboard.stockOk':'Alle Vorräte liegen über dem Minimum.','dashboard.todayTasks':'Heutige Aufgaben','dashboard.waiting':'{count} offen','dashboard.calendar':'Kalender','dashboard.todayDone':'Für heute ist alles erledigt.','dashboard.activity':'Was zu Hause ansteht','dashboard.activityHint':'Schneller Überblick über Termine und Vorräte','dashboard.freezerUse':'{name} sollte verbraucht werden','dashboard.inFreezerSince':'Eingefroren seit {date} · {progress} % der empfohlenen Zeit','dashboard.expiring':'{name} läuft bald ab','dashboard.useBy':'Verbrauchen bis {date}','dashboard.noDeadlines':'Keine anstehenden Termine.',
  'pantry.title':'Was wir zu Hause haben','pantry.subtitle':'Behalte den Überblick, fülle mit einem Klick nach und lass nichts ausgehen.','pantry.add':'Artikel hinzufügen','pantry.search':'Vorräte durchsuchen…','pantry.restock':'Nachfüllen','pantry.expired':'Abgelaufen','pantry.minimum':'Kanban-Minimum','pantry.until':'bis {date}','pantry.noExpiry':'kein Ablaufdatum','pantry.empty':'Keine Artikel entsprechen dem Filter.',
  'freezer.title':'Gefrierschrank ohne Überraschungen','freezer.subtitle':'Empfohlene Zeiten bei −18 °C helfen, die beste Qualität zu erhalten.','freezer.add':'In den Gefrierschrank','freezer.goodToKnow':'Gut zu wissen','freezer.fact':'Lebensmittel, die dauerhaft bei −18 °C gelagert werden, bleiben fast unbegrenzt sicher. Die Zeiten unten beziehen sich auf Geschmack und Qualität.','freezer.contents':'Inhalt des Gefrierschranks','freezer.consume':'Jetzt verbrauchen','freezer.soon':'Bald','freezer.ok':'In Ordnung','freezer.frozen':'Eingefroren {date} · empfohlen {months} Mon.','freezer.guide':'Gefrierleitfaden','freezer.quality':'Qualitätsempfehlungen','freezer.source':'Quelle: USDA Food Safety',
  'shopping.title':'Einkäufe im Griff','shopping.subtitle':'Listen nach Geschäft, schnelles Abhaken und direkte Übernahme in die Vorräte.','shopping.allArchived':'Alle aktiven Listen sind archiviert.','shopping.restoreFirst':'Stelle zuerst eine Liste aus dem Archiv wieder her.','shopping.archived':'Liste „{name}“ wurde archiviert','shopping.restored':'Liste wurde wiederhergestellt','shopping.finishedOne':'Einkauf abgeschlossen · 1 Artikel zu Vorräten hinzugefügt','shopping.finishedMany':'Einkauf abgeschlossen · {count} Artikel zu Vorräten hinzugefügt','shopping.remaining':'{count} übrig','shopping.newList':'Neue Liste','shopping.archive':'Archiv ({count})','shopping.archiveAction':'Archivieren','shopping.scan':'Code scannen','shopping.progress':'Einkaufsfortschritt','shopping.preselected':'für Vorräte vorausgewählt','shopping.enterPrice':'Preis eingeben','shopping.spending':'Zwischensumme','shopping.done':'Fertig','shopping.finishEyebrow':'Einkauf abschließen','shopping.finishTitle':'Was soll zu den Vorräten?','shopping.finishText':'Abgehakte Artikel werden als erledigt markiert. Wähle nur Lebensmittel aus, die du zusätzlich in den Vorräten speichern möchtest.','shopping.finishNote':'{selected} von {total} Artikeln werden zu den Vorräten hinzugefügt.','shopping.confirm':'Abschluss bestätigen','shopping.archivedLists':'Archivierte Listen','shopping.archivedHint':'Für später aufbewahrt',
  'recipes.title':'Was kochen wir heute?','recipes.subtitle':'Lieblingsrezepte verbunden mit Einkauf und Vorräten.','recipes.new':'Neues Rezept','recipes.search':'Rezept oder Zutat suchen…','recipes.servings':'{count} Portionen','recipes.addShopping':'Zutaten zur Einkaufsliste','recipes.ingredientsAdded':'Zutaten für „{name}“ zum Einkauf hinzugefügt','recipes.favorite':'Lieblingsrezept {name}',
  'todos.title':'Was erledigt werden muss','todos.subtitle':'Haushaltsaufgaben an einem Ort und im Zusammenhang.','todos.add':'Aufgabe hinzufügen','todos.selectedDay':'Ausgewählter Tag','todos.empty':'Für diesen Tag ist nichts geplant.','weekdays':'Mo,Di,Mi,Do,Fr,Sa,So',
  'modal.editItem':'Artikel bearbeiten','modal.addPantry':'Zu Vorräten hinzufügen','modal.addFreezer':'In den Gefrierschrank','modal.addShopping':'Zum Einkauf hinzufügen','modal.newTodo':'Neue Aufgabe','modal.scanCode':'Code scannen','modal.editRecipe':'Rezept bearbeiten','modal.newRecipe':'Neues Rezept','modal.name':'Name','modal.selectOrType':'Auswählen oder neuen Wert eingeben','modal.priceCzk':'Preis in CZK','modal.purchaseDate':'Kaufdatum','modal.expiryOptional':'Verbrauchen bis (optional)','modal.barcode':'EAN / Barcode','modal.scan':'Scannen','modal.imageUrl':'Bild-URL','modal.photo':'Eigenes Foto','modal.productPreview':'Produktvorschau','modal.choosePhoto':'Foto aufnehmen oder auswählen','modal.changePhoto':'Foto ändern','modal.freezerCategory':'Kategorie und empfohlene Dauer','modal.freezeDate':'Einfrierdatum','modal.note':'Notiz','modal.list':'Liste','modal.estimatedPrice':'Geschätzter Preis in CZK','modal.addToPantry':'Beim Einkaufsabschluss für Vorräte vorauswählen','modal.todoQuestion':'Was muss erledigt werden?','modal.date':'Datum','modal.family':'Familie','modal.other':'Sonstiges','modal.household':'Haushalt','modal.emoji':'Emoji','modal.recipeName':'Rezeptname','modal.minutes':'Zeit in Minuten','modal.servings':'Portionen','modal.tags':'Tags, durch Kommas getrennt','modal.instructions':'Zubereitung','modal.instructionsPlaceholder':'Beschreibe die einzelnen Zubereitungsschritte…','modal.exampleItem':'z. B. rote Bohnen','modal.exampleFreezer':'z. B. Hähnchenschenkel','modal.examplePortion':'z. B. Portion 500 g','modal.whatBuy':'Was soll gekauft werden?','modal.exampleTodo':'z. B. Kühlschrank reinigen','modal.exampleRecipe':'z. B. Paprikahähnchen','modal.tagsPlaceholder':'Schnell, Abendessen, Vegetarisch','modal.codeScanned':'Code {code} gescannt','modal.eanLoaded':'EAN {code} geladen','modal.itemUpdated':'Artikel aktualisiert','modal.itemPantryAdded':'Artikel zu Vorräten hinzugefügt','modal.itemFreezerAdded':'Artikel zum Gefrierschrank hinzugefügt','modal.itemShoppingAdded':'Artikel zum Einkauf hinzugefügt','modal.todoAdded':'Aufgabe hinzugefügt','modal.recipeUpdated':'Rezept aktualisiert','modal.recipeAdded':'Rezept hinzugefügt','modal.toTaste':'nach Geschmack',
  'ingredients.title':'Zutaten','ingredients.hint':'Aus Vorräten wählen oder selbst eingeben','ingredients.addRow':'Zeile hinzufügen','ingredients.item':'Zutat','ingredients.amount':'Menge der Zutat {count}','ingredients.remove':'Zutat {count} entfernen','ingredients.amountPlaceholder':'z. B. 500 g',
  'scanner.aim':'Richte die Rückkamera auf einen Barcode oder QR-Code.','scanner.https':'Die Kamera benötigt HTTPS. Du kannst die EAN vorerst manuell eingeben.','scanner.allow':'Erlaube den Kamerazugriff und halte den Code im Rahmen.','scanner.denied':'Der Kamerazugriff wurde verweigert. Erlaube ihn in den Browsereinstellungen.','scanner.failed':'Die Kamera konnte nicht gestartet werden. Prüfe, ob eine andere App sie verwendet.','scanner.recognizing':'Code wird vom Foto gelesen…','scanner.notFound':'Auf dem Foto wurde kein Code gefunden. Versuche eine Nahaufnahme ohne Spiegelung.','scanner.stop':'Stoppen','scanner.live':'Live-Kamera','scanner.photo':'Code fotografieren',
  'nutrition.title':'Nährwerte','nutrition.kcal':'kcal','nutrition.per100':'Werte pro 100 g eingeben','nutrition.catalog':'Kalorientabellen','nutrition.searchFood':'Nach {name} suchen','nutrition.openCatalog':'Lebensmittelkatalog öffnen','nutrition.forAmount':'Für Menge berechnen','nutrition.carbs':'Kohlenhydrate','nutrition.fat':'Fett','nutrition.protein':'Eiweiß','nutrition.fiber':'Ballaststoffe','nutrition.amountAria':'Menge für Nährwertberechnung','error.photoRead':'Das Foto konnte nicht gelesen werden.','error.photoFormat':'Dieses Bildformat kann nicht verwendet werden.',
})

Object.assign(messages.cs, { 'nav.products': 'Databáze potravin', 'nav.weight': 'Hmotnost', 'nutrition.sugars': 'z toho cukry' })
Object.assign(messages.en, { 'nav.products': 'Food database', 'nav.weight': 'Weight', 'nutrition.sugars': 'of which sugars' })
Object.assign(messages.de, { 'nav.products': 'Lebensmitteldatenbank', 'nav.weight': 'Gewicht', 'nutrition.sugars': 'davon Zucker' })

type I18nContextValue = {
  language: Language
  locale: string
  setLanguage: (language: Language) => void
  t: (key: string, values?: TranslationValues) => string
}

const I18nContext = createContext<I18nContextValue | null>(null)

function initialLanguage(): Language {
  try {
    const saved = JSON.parse(localStorage.getItem('grocy-homie-settings-v1') || '{}') as { language?: Language }
    return languages.some(item => item.value === saved.language) ? saved.language! : 'cs'
  } catch { return 'cs' }
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(initialLanguage)
  useEffect(() => { document.documentElement.lang = language }, [language])
  const value = useMemo<I18nContextValue>(() => ({
    language,
    locale: locales[language],
    setLanguage,
    t: (key, values) => {
      const template = messages[language][key] ?? messages.cs[key] ?? key
      return Object.entries(values ?? {}).reduce((text, [name, replacement]) => text.replaceAll(`{${name}}`, String(replacement)), template)
    },
  }), [language])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export function useI18n() {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used inside I18nProvider')
  return context
}
