name: Grocy Homie
version: "1.7.3"
slug: grocy_homie
description: Moderní správa domácích zásob, nákupů, receptů a úkolů.
url: https://github.com/BeefyDaddy2510/kanban-grocery
arch:
  - amd64
  - aarch64
init: false
backup: cold
ingress: true
ingress_port: 8080
panel_title: Grocy Homie
panel_icon: mdi:basket-fill
panel_admin: false
image: ghcr.io/beefydaddy2510/kanban-grocery
legacy: true
